name:                racket-pretty-printer
version:             0.1.0.0
github:              "githubuser/racket-pretty-printer"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/racket-pretty-printer#readme>

dependencies:
- base >= 4.7 && < 5
- prettyprinter
- attoparsec 
- text
- optparse-applicative

library:
  source-dirs: src

executables:
  racket-pretty-printer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - racket-pretty-printer

tests:
  racket-pretty-printer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - racket-pretty-printer
